apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  selector:
    app: orders
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80          # Public-facing port
      targetPort: 8080  # Your app's port inside container
